# Generated by Django 4.2.1 on 2023-05-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_name", models.CharField(max_length=100)),
                ("store_code", models.CharField(max_length=10)),
                ("store_segment", models.CharField(max_length=100)),
                ("address_dong", models.CharField(max_length=100)),
                ("address_road", models.CharField(max_length=100)),
                ("longitude", models.FloatField()),
                ("latitude", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="UserInputModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_location", models.CharField(max_length=100)),
                ("store_select", models.CharField(max_length=100)),
                ("store_area", models.IntegerField()),
            ],
        ),
    ]
